-- Baseline schema: links and their click events.
CREATE TABLE link (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code             VARCHAR(32)   NOT NULL,
    target_url       VARCHAR(2048) NOT NULL,
    created_at       TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    click_count      BIGINT        NOT NULL DEFAULT 0,
    last_accessed_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT uk_link_code UNIQUE (code)
);

CREATE TABLE click_event (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    link_id       BIGINT       NOT NULL REFERENCES link (id) ON DELETE CASCADE,
    occurred_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    referrer_host VARCHAR(255),
    visitor_hash  VARCHAR(64)
);

CREATE INDEX idx_click_event_link_time ON click_event (link_id, occurred_at);
