package com.agentic.orchestrator.agent;

import com.agentic.orchestrator.artifact.CodebaseAnalysis;
import com.agentic.orchestrator.artifact.DesignDoc;
import com.agentic.orchestrator.artifact.ImplementationResult;
import com.agentic.orchestrator.artifact.ReleaseReadiness;
import com.agentic.orchestrator.artifact.RequirementSpec;
import com.agentic.orchestrator.artifact.SecurityReport;
import com.agentic.orchestrator.artifact.TaskPlan;
import com.agentic.orchestrator.artifact.ThreatModel;
import com.agentic.orchestrator.artifact.ValidationReport;
import com.agentic.orchestrator.engine.DecisionRecord;
import com.agentic.orchestrator.engine.RunSnapshot;
import com.agentic.orchestrator.workflow.WorkflowTemplates;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.time.Duration;
import java.util.List;

/** Markdown for the reviewer: built only from accepted artifacts and the decision log. */
final class Reports {

    private final AgentContext ctx;
    private final RequirementSpec spec;
    private final DesignDoc design;
    private final TaskPlan plan;
    private final ImplementationResult implementation;
    private final ValidationReport validation;
    private final SecurityReport security;
    private final ReleaseReadiness readiness;
    private final RunSnapshot run;

    Reports(AgentContext ctx, ObjectMapper json) {
        this.ctx = ctx;
        this.spec = ctx.require(WorkflowTemplates.REQUIREMENTS, RequirementSpec.class);
        this.design = ctx.require(WorkflowTemplates.DESIGN, DesignDoc.class);
        this.plan = ctx.require(WorkflowTemplates.PLAN, TaskPlan.class);
        this.implementation = ctx.require(WorkflowTemplates.IMPLEMENTATION, ImplementationResult.class);
        this.validation = ctx.require(WorkflowTemplates.VALIDATION, ValidationReport.class);
        this.security = ctx.require(WorkflowTemplates.SECURITY_REVIEW, SecurityReport.class);
        this.readiness = ctx.require(WorkflowTemplates.RELEASE_READINESS, ReleaseReadiness.class);
        this.run = ctx.runView().get();
    }

    String pullRequest(List<String> changed) {
        StringBuilder md = new StringBuilder("# ").append(spec.title()).append("\n\n").append(spec.summary()).append("\n\n");
        md.append("## Changes\n\n");
        implementation.tasks().forEach(t -> md.append("- **").append(t.taskId()).append("** ").append(t.summary()).append('\n'));
        md.append("\n## Files (").append(changed.size()).append(")\n\n");
        changed.forEach(f -> md.append("- `").append(f).append("`\n"));
        md.append("\n## Acceptance criteria\n\n");
        spec.acceptanceCriteria().forEach(ac -> md.append("- [x] ").append(ac.id()).append(": ").append(ac.description()).append('\n'));
        md.append("\n## Validation\n\n- Tests: ").append(validation.testsRun()).append(" run, ")
                .append(validation.failures()).append(" failed (`").append(validation.command()).append("`)\n- Security: ")
                .append(security.summary()).append("\n- Release check: ").append(readiness.summary()).append("\n");
        md.append("\n## Rollback\n\n").append(design.rollbackPlan()).append('\n');
        md.append("\n---\nGenerated by run `").append(run.runId()).append("` (trace `").append(run.traceId()).append("`)\n");
        return md.toString();
    }

    String engineeringSummary(List<String> changed) {
        StringBuilder md = new StringBuilder("# Engineering summary: ").append(spec.title()).append("\n\n");
        md.append("Run `").append(run.runId()).append("`, scenario `").append(run.scenarioId()).append("`, approvals ")
                .append(run.approvalPolicy()).append(", duration ").append(Duration.ofMillis(run.durationMs()).toSeconds())
                .append("s, ").append(run.agentInvocations()).append(" agent invocations.\n\n");

        md.append("## 1. Requirement understanding\n\n").append(spec.summary()).append("\n\n");
        md.append("**Change type:** ").append(spec.changeType()).append("\n\n**Acceptance criteria**\n\n");
        spec.acceptanceCriteria().forEach(ac -> md.append("- ").append(ac.id()).append(": ").append(ac.description()).append('\n'));
        if (!ctx.clarifications().isEmpty()) {
            md.append("\n**Ambiguities resolved with the stakeholder**\n\n");
            ctx.clarifications().forEach((id, text) -> md.append("- ").append(id).append(": ").append(text).append('\n'));
        }
        md.append("\n**Assumptions**\n\n");
        list(md, spec.assumptions());
        md.append("\n**Out of scope**\n\n");
        list(md, spec.outOfScope());

        ctx.optional(WorkflowTemplates.ANALYSIS, CodebaseAnalysis.class).ifPresent(a -> {
            md.append("\n## 2. Codebase reasoning\n\n").append(a.impact().summary()).append("\n\n");
            a.impact().impactedFiles().forEach(f -> md.append("- `").append(f.path()).append("` (").append(f.changeKind())
                    .append("): ").append(f.reason()).append('\n'));
            if (!a.impact().dataFlows().isEmpty()) {
                md.append("\nData flows:\n\n");
                list(md, a.impact().dataFlows());
            }
        });

        md.append("\n## 3. Design and rationale\n\n").append(design.overview()).append("\n\n**Impacts:** ")
                .append(design.impacts()).append("\n\n**Decisions**\n\n");
        design.decisions().forEach(d -> md.append("- ").append(d.decision()).append(": ").append(d.rationale()).append('\n'));
        md.append("\n**Alternatives considered**\n\n");
        design.alternatives().forEach(a -> md.append("- ").append(a.option()).append(": rejected because ").append(a.whyNotChosen()).append('\n'));
        ctx.optional(WorkflowTemplates.THREAT_MODEL, ThreatModel.class).ifPresent(t -> {
            md.append("\n**Threat model**\n\n");
            t.threats().forEach(th -> md.append("- [").append(th.severity()).append("] ").append(th.category()).append(": ")
                    .append(th.description()).append(" -> ").append(th.mitigation()).append('\n'));
        });

        md.append("\n## 4. Plan (task decomposition)\n\n").append(plan.rationale()).append("\n\n| Task | Kind | Depends on | Covers |\n|---|---|---|---|\n");
        plan.tasks().forEach(t -> md.append("| ").append(t.id()).append(" ").append(t.title()).append(" | ").append(t.kind())
                .append(" | ").append(t.dependsOn()).append(" | ").append(t.coversCriteria()).append(" |\n"));

        md.append("\n## 5. Artifacts\n\n| Artifact | State | Produced by | Hash |\n|---|---|---|---|\n");
        run.artifacts().forEach(a -> md.append("| ").append(a.ref()).append(" | ").append(a.state()).append(" | ")
                .append(a.producedBy()).append(" | `").append(a.contentHash()).append("` |\n"));
        md.append("\nCode change: ").append(changed.size()).append(" files, see `change.patch` and `COMMITS.txt`.\n");

        md.append("\n## 6. Validation, risks and trade-offs\n\n- Tests: ").append(validation.testsRun()).append(" run, ")
                .append(validation.failures()).append(" failures\n- Security: ").append(security.summary())
                .append("\n- Release readiness: ").append(readiness.summary()).append("\n\n**Checklist**\n\n");
        readiness.checklist().forEach(c -> md.append("- ").append(c.passed() ? "[x] " : "[ ] ").append(c.item())
                .append(": ").append(c.evidence()).append('\n'));
        md.append("\n**Risks**\n\n");
        design.risks().forEach(r -> md.append("- ").append(r.description()).append(" (likelihood ").append(r.likelihood())
                .append(", impact ").append(r.impact()).append("): ").append(r.mitigation()).append('\n'));
        md.append("\n**Test strategy:** ").append(design.testStrategy()).append("\n\n**Rollback plan:** ")
                .append(design.rollbackPlan()).append('\n');

        md.append("\n## 7. Execution and governance\n\n| Stage | Status | Executions | Agent |\n|---|---|---|---|\n");
        // This report is written by the publish stage itself, so that row is still in progress.
        run.stages().forEach(s -> md.append("| ").append(s.id()).append(" | ")
                .append(s.id().equals(ctx.stage().id()) ? "SUCCEEDED (writing this report)" : s.status()).append(" | ")
                .append(s.executions()).append(" | ").append(s.agent()).append(" |\n"));
        md.append("\nCounters: ").append(run.counters()).append("\n\n**Decision log**\n\n");
        for (DecisionRecord d : run.decisions()) {
            md.append("- #").append(d.id()).append(" ").append(d.type()).append(" by ").append(d.actor()).append(": ")
                    .append(d.summary()).append(d.rationale() == null || d.rationale().isBlank() ? "" : " (" + d.rationale() + ")")
                    .append('\n');
        }
        md.append("\n## 8. Limitations\n\n")
                .append("- Generated code is validated by the project's own test suite and static policy checks; ")
                .append("it still requires human code review before merge.\n")
                .append("- Security review is rule-based (secrets, dangerous APIs, PII logging, input validation) and is not a substitute for a penetration test.\n")
                .append("- The workspace build runs locally; no deployment is performed by this pipeline.\n");
        return md.toString();
    }

    private static void list(StringBuilder md, List<String> items) {
        if (items == null || items.isEmpty()) {
            md.append("- none\n");
        } else {
            items.forEach(i -> md.append("- ").append(i).append('\n'));
        }
    }
}
