package com.agentic.orchestrator.agent;

import com.agentic.orchestrator.artifact.ChangeAction;
import com.agentic.orchestrator.artifact.ChangeSet;
import com.agentic.orchestrator.artifact.DesignDoc;
import com.agentic.orchestrator.artifact.DocsUpdate;
import com.agentic.orchestrator.artifact.FileChange;
import com.agentic.orchestrator.artifact.RequirementSpec;
import com.agentic.orchestrator.artifact.TaskChangeSet;
import com.agentic.orchestrator.engine.StageOutcome;
import com.agentic.orchestrator.workflow.WorkflowTemplates;

import java.util.List;
import java.util.Locale;

/** Deterministic fallback: documentation generated from the accepted requirement and design artifacts. */
public class TemplateDocumentationAgent implements Agent {

    @Override
    public String name() {
        return "documentation-template";
    }

    @Override
    public StageOutcome execute(AgentContext ctx) {
        RequirementSpec spec = ctx.require(WorkflowTemplates.REQUIREMENTS, RequirementSpec.class);
        DesignDoc design = ctx.require(WorkflowTemplates.DESIGN, DesignDoc.class);
        String slug = spec.title().toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9]+", "-").replaceAll("(^-|-$)", "");
        StringBuilder page = new StringBuilder("# ").append(spec.title()).append("\n\n").append(spec.summary()).append("\n\n");
        page.append("## Behaviour\n\n");
        spec.acceptanceCriteria().forEach(ac -> page.append("- **").append(ac.id()).append("** ").append(ac.description()).append('\n'));
        page.append("\n## API changes\n\n");
        if (design.apiChanges() == null || design.apiChanges().isEmpty()) {
            page.append("None.\n");
        } else {
            design.apiChanges().forEach(api -> page.append("- `").append(api.method()).append(' ').append(api.path())
                    .append("`: ").append(api.description()).append(api.breaking() ? " **(breaking)**" : "").append('\n'));
        }
        page.append("\n## Design notes\n\n").append(design.overview()).append("\n\n## Rollback\n\n")
                .append(design.rollbackPlan()).append('\n');
        String existing = ctx.workspace().read("CHANGELOG.md").orElse("# Changelog\n");
        String entry = "\n## Unreleased\n\n- " + spec.title() + ": " + spec.summary() + "\n";
        String changelog = existing.startsWith("# Changelog")
                ? existing.replaceFirst("# Changelog\\R?", "# Changelog\n" + entry)
                : "# Changelog\n" + entry + "\n" + existing;
        List<FileChange> changes = List.of(
                new FileChange("docs/" + slug + ".md", ChangeAction.CREATE, page.toString()),
                new FileChange("CHANGELOG.md", ctx.workspace().read("CHANGELOG.md").isPresent()
                        ? ChangeAction.MODIFY : ChangeAction.CREATE, changelog));
        DocsUpdate update = new DocsUpdate("Template documentation for " + spec.title(), changes);
        return StageOutcome.success(update, new ChangeSet(List.of(new TaskChangeSet("DOCS", update.summary(), changes,
                "Generated by deterministic template (model unavailable)"))), "template");
    }
}
